import re


class SQLQueryValidator:
    """
    Validates SQL queries generated by the LLM before execution.
    Ensures only safe read-only queries are allowed.
    """

    # dangerous SQL operations
    FORBIDDEN_KEYWORDS = [
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "TRUNCATE",
        "CREATE",
        "GRANT",
        "REVOKE",
    ]

    @classmethod
    def validate(cls, query: str) -> tuple[bool, str | None]:
        """
        Validate SQL query safety.

        Returns:
            (is_valid, error_message)
        """

        if not query:
            return False, "Query is empty"

        query_clean = query.strip()

        # allow only SELECT queries
        if not query_clean.lower().startswith("select"):
            return False, "Only SELECT queries are allowed"

        # block dangerous keywords
        for keyword in cls.FORBIDDEN_KEYWORDS:
            pattern = rf"\b{keyword}\b"

            if re.search(pattern, query_clean, re.IGNORECASE):
                return False, f"Forbidden SQL keyword detected: {keyword}"

        return True, None